apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-home
  labels:
    type: local
spec:
  capacity:
    storage: 13Gi
  hostPath:
    path: "/home/kube-vol"
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem

